// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWf_3YI01HGu_zi3i1rUcQusEx54LYJwI',
    appId: '1:489937097048:android:e45f347d4f8d665c8bd52d',
    messagingSenderId: '489937097048',
    projectId: 'habit-list-f4e87',
    storageBucket: 'habit-list-f4e87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp4KigGnhL3buw6pFdTjKNv0gPp32MTqw',
    appId: '1:489937097048:ios:117b6077fa96b99d8bd52d',
    messagingSenderId: '489937097048',
    projectId: 'habit-list-f4e87',
    storageBucket: 'habit-list-f4e87.appspot.com',
    iosClientId: '489937097048-f2gvl9e5af09p769jehkd8025s1mqpr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitList',
  );
}
